image: python:3.8

stages:
    - deploy

before_script:
    - pip install -r requirements.txt

heroku:
    stage: deploy
    script:
        - apt update -qy
        - apt install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
    only:
        - master
    environment:
        name: heroku
        url: $ENV_URL
