# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: python:3.8
stages:
- deploy
- test
before_script:
- pip install -r requirements.txt
heroku:
  stage: deploy
  script:
  - apt update -qy
  - apt install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
  - master
  environment:
    name: heroku
    url: "$ENV_URL"
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
